// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHF6to1CXrirrZfpsZSJ8lRshu5XxIsX0',
    appId: '1:308992706081:web:017ecc31222c56dccf0560',
    messagingSenderId: '308992706081',
    projectId: 'lottoblog-e4927',
    authDomain: 'lottoblog-e4927.firebaseapp.com',
    storageBucket: 'lottoblog-e4927.appspot.com',
    measurementId: 'G-SQ1JE3HDK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC0enJc60WuY8VHSyYMAW7W_oOD2CMVSE',
    appId: '1:308992706081:android:db1dea23a754cb92cf0560',
    messagingSenderId: '308992706081',
    projectId: 'lottoblog-e4927',
    storageBucket: 'lottoblog-e4927.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD64PhFCd5qL3OYmsA9Kx8GYCVwy-LnPVA',
    appId: '1:308992706081:ios:a5b871bf438cb422cf0560',
    messagingSenderId: '308992706081',
    projectId: 'lottoblog-e4927',
    storageBucket: 'lottoblog-e4927.appspot.com',
    iosBundleId: 'com.seonho.lottoblog',
  );
}
